name: brandpulse

services:

  backend:
    build: .
    container_name: brandpulse-backend

    ports:
      - "8000:8000"

    volumes:
      - .:/app

    env_file:
      - .env

    depends_on:
      - postgres

  postgres:
    image: postgres:16

    container_name: brandpulse-postgres

    restart: always

    environment:
      POSTGRES_USER: brandpulse
      POSTGRES_PASSWORD: brandpulse123
      POSTGRES_DB: brandpulse

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: